export const PARTICIPANT_RESET_PAS_SET_VALUE:'PARTICIPANT_RESET_PAS_SET_VALUE' = 'PARTICIPANT_RESET_PAS_SET_VALUE';
export const PARTICIPANT_RESET_PAS_SUBMIT:'PARTICIPANT_RESET_PAS_SUBMIT' = 'PARTICIPANT_RESET_PAS_SUBMIT';
export const PARTICIPANT_RESET_PAS_SUBMIT_SUCCESS:'PARTICIPANT_RESET_PAS_SUBMIT_SUCCESS' = 'PARTICIPANT_RESET_PAS_SUBMIT_SUCCESS';
export const PARTICIPANT_RESET_PAS_SUBMIT_FAILED:'PARTICIPANT_RESET_PAS_SUBMIT_FAILED' = 'PARTICIPANT_RESET_PAS_SUBMIT_FAILED';  