export const PARTICIPANT_LOGIN_FORM_SET_VALUE = 'PARTICIPANT_LOGIN_FORM_SET_VALUE';
export const PARTICIPANT_LOGIN_FORM_SUBMIT = 'PARTICIPANT_LOGIN_FORM_SUBMIT';
export const  PARTICIPANT_LOGIN_FORM_SUBMIT_SUCCESS = 'PARTICIPANT_LOGIN_FORM_SUBMIT_SUCCESS';
export const PARTICIPANT_LOGIN_FORM_SUBMIT_FAILED = 'PARTICIPANT_LOGIN_FORM_SUBMIT_FAILED'; 